from dotenv import load_dotenv
import google.generativeai as genai
import os


def generate_gemini_response(promt):
    """
    Generates a response using the google gemini model.

    Args:
      prompt: The input promt for the model.

    Returns:
       The text response generated by gemini model.
    """
    load_dotenv()
    genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
    my_config= genai.get_model('models/gemini-pro') # default values
    # genai.types.GenerationConfig(temperature=0,top_k=0,top_p=0)
    model=genai.GenerativeModel('gemini-pro')
    answer=model.generate_content(promt,generation_config=my_config)
    return answer.text